export const SETTINGS_CONFIG = {
  searxng: {
    enabled: false,
    baseUrl: "https://search.crystelf.top/",
    timeoutMs: 8000,
    defaultLimit: 5,
    maxLimit: 8,
  },
  webReader: {
    enabled: true,
    useWorkingModel: true,
    timeoutMs: 10_000,
    maxHtmlBytes: 1_500_000,
    maxExtractedChars: 12_000,
    browserTimeoutMs: 15_000,
    allowedContentTypes: ["text/html", "application/xhtml+xml", "text/plain"],
  },
  audio: {
    enabled: true,
    baseUrl: "http://localhost:3939",
    apiKey: "fufu",
    timeoutMs: 40_000,
  },
  blacklistGroups: [],
  whitelistGroups: [],
  mediaAnalysisBlacklistUsers: [],
  maxSessions: 100,
  enableExternalSkills: true,
  allowedExternalSkills: [],
  stream: true,
  enableTypingDelay: true,
  typingDelayMaxTotalMs: 10_000,
  enableMarkdownScreenshot: true,
  debug: false,
  outputLengthConstraintStrength: "medium",
  toolCallConstraintStrength: "medium",
  emojiUsageConstraintStrength: "medium",
  audioUsageConstraintStrength: "medium",
  markdownUsageConstraintStrength: "medium",
  groupStructuredHistoryTtlMs: 10 * 60_000,
  nicknames: ["miku", "未来", "初音"],
  cooldownAfterReplyMs: 20_000,
  aiRequestLimits: {
    userRpm: 3,
    groupRpm: 6,
    windowMs: 60_000,
  },
  dynamicDelay: {
    enabled: true,
    interactionWindowMs: 60_000,
    baseDelayMs: 30_000,
    maxDelayMs: 300_000,
  },
};
